### ISSUE TITLE
When the lock fails to acquire, it runs the block anyway

### ISSUE THREAD

**Issue by mkdynamic** [marioizquierdo/mario-redis-lock#1]
This seems to entirely defeat the purpose of the mutex and allows multiple callers to enter the critical section (i.e. the block) at the same time.

``` ruby
# Acquire a lock. Use options to override defaults.
# This method makes sure to release the lock as soon as the block is finalized.
def self.acquire(opts={}, &block)
  lock = RedisLock.new(opts)
  if lock.acquire
    begin
      block.call(lock)
    ensure
      lock.release
    end
  else
    block.call(lock)
  end
end
```

If the lock fails to acquire, it should raise an exception or return nil/false, rather than calling the block.

Here is a simple test to reproduce:

``` ruby
require 'redis_lock'
Thread.new { RedisLock.acquire(key: "foo") { sleep } } # thread now holds the lock
RedisLock.acquire(key: "foo", retry_timeout: 1) { puts "hello" } # this runs after 1 second -- it should not
```

**Comment by marioizquierdo** [comment]
The `RedisLock.acquire` method block is supposed to be invoked with a `lock` parameter, to then check if it's locked or not:

You should try this:

``` ruby
require 'redis_lock'
RedisLiock.acquire(key: "foo") { |lock| sleep if lock.acquired? }
RedisLock.acquire(key: "foo", retry_timeout: 1) { |lock| puts "hello" if lock.acquired? }
```

That said, I think you are right. Using the acquire block with no `|lock|` parameter should either "work as expected" (be executed only if the lock is locked) or raise a descriptive exception saying that the lock parameter is needed.

Which one would you feel makes more sense?

**Comment by mkdynamic** [comment]
Ah, I see. That makes total sense, I just failed to read the `README.md` properly. Sorry :)

It would be nice if `acquire` checked the block arity was 1, but I don't think it's necessary.

**Comment by marioizquierdo** [comment]
Thanks!
Raising an error if arity is not 1 would make it clear.
It is a breaking change but I think I will implement it anyways since it prevents surprising behavior.

**Comment by marioizquierdo** [comment]
@mkdynamic I simplified the README file a little bit and now the `RedisLock.acquire` method raises an `ArgumentException` explaining that the block should have a lock parameter.

Thank you for your feedback.

**Comment by mkdynamic** [comment]
@marioizquierdo :thumbsup: thanks!
